# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
import dataclasses
from typing import Any, Optional


@dataclasses.dataclass()
class Record:
    id: int
    name: str
    note: Optional[str]
    payload: bytes
    score: Optional[float]
    dynamic_value: Optional[Any]
