# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
# source: query.sql
import dataclasses
from typing import Any, AsyncIterator, Iterator, Optional, Protocol, Sequence, cast

from querytest import models


class _DBAPICursor(Protocol):
    @property
    def rowcount(self) -> int:
        pass

    def fetchone(self) -> Optional[Sequence[Any]]:
        pass

    def fetchall(self) -> Sequence[Sequence[Any]]:
        pass


class _DBAPIConnection(Protocol):
    def execute(self, sql: str, parameters: tuple[Any, ...], /) -> _DBAPICursor:
        pass


class _AsyncDBAPIConnection(Protocol):
    async def execute(self, sql: str, parameters: tuple[Any, ...], /) -> _DBAPICursor:
        pass


DELETE_RECORD = """-- name: delete_record \\:execrows
DELETE FROM records WHERE id = ?
"""


DELETE_RECORDS_RETURNING = """-- name: delete_records_returning \\:execrows
DELETE FROM records
WHERE name = ?
RETURNING id
"""


GET_RECORD = """-- name: get_record \\:one
SELECT id, name, note, payload, score, dynamic_value
FROM records
WHERE id = ?
"""


GET_RECORD_NAME = """-- name: get_record_name \\:one
SELECT name FROM records WHERE id = ?
"""


GET_RECORD_NOTE = """-- name: get_record_note \\:one
SELECT note FROM records WHERE id = ?
"""


INSERT_RECORD = """-- name: insert_record \\:one
INSERT INTO records (name, note, payload, score, dynamic_value)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, note, payload, score, dynamic_value
"""


@dataclasses.dataclass()
class InsertRecordParams:
    name: str
    note: Optional[str]
    payload: bytes
    score: Optional[float]
    dynamic_value: Optional[Any]


LIST_RECORD_NOTES = """-- name: list_record_notes \\:many
SELECT note FROM records ORDER BY id
"""


LIST_RECORDS = """-- name: list_records \\:many
SELECT id, name, note, payload, score, dynamic_value
FROM records
WHERE name = ? OR note = ?
ORDER BY id
"""


RENAME_RECORD = """-- name: rename_record \\:exec
UPDATE records SET name = ? WHERE id = ?
"""


class Querier:
    def __init__(self, conn: _DBAPIConnection):
        self._conn = conn

    def delete_record(self, *, id: int) -> int:
        result = self._conn.execute(DELETE_RECORD, (id,))
        return result.rowcount

    def delete_records_returning(self, *, name: str) -> int:
        result = self._conn.execute(DELETE_RECORDS_RETURNING, (name,))
        result.fetchall()
        return result.rowcount

    def get_record(self, *, id: int) -> Optional[models.Record]:
        cursor = self._conn.execute(GET_RECORD, (id,))
        row = cursor.fetchone()
        if row is None:
            return None
        return models.Record(
            id=row[0],
            name=row[1],
            note=row[2],
            payload=row[3],
            score=row[4],
            dynamic_value=row[5],
        )

    def get_record_name(self, *, id: int) -> Optional[str]:
        cursor = self._conn.execute(GET_RECORD_NAME, (id,))
        row = cursor.fetchone()
        if row is None:
            return None
        return cast(str, row[0])

    def get_record_note(self, *, id: int) -> Optional[Optional[str]]:
        cursor = self._conn.execute(GET_RECORD_NOTE, (id,))
        row = cursor.fetchone()
        if row is None:
            return None
        return cast(Optional[str], row[0])

    def insert_record(self, arg: InsertRecordParams) -> Optional[models.Record]:
        cursor = self._conn.execute(INSERT_RECORD, (arg.name, arg.note, arg.payload, arg.score, arg.dynamic_value))
        row = cursor.fetchone()
        if row is None:
            return None
        return models.Record(
            id=row[0],
            name=row[1],
            note=row[2],
            payload=row[3],
            score=row[4],
            dynamic_value=row[5],
        )

    def list_record_notes(self) -> Iterator[Optional[str]]:
        cursor = self._conn.execute(LIST_RECORD_NOTES, ())
        result = cursor.fetchall()
        for row in result:
            yield cast(Optional[str], row[0])

    def list_records(self, *, name: str) -> Iterator[models.Record]:
        cursor = self._conn.execute(LIST_RECORDS, (name, name))
        result = cursor.fetchall()
        for row in result:
            yield models.Record(
                id=row[0],
                name=row[1],
                note=row[2],
                payload=row[3],
                score=row[4],
                dynamic_value=row[5],
            )

    def rename_record(self, *, name: str, id: int) -> None:
        self._conn.execute(RENAME_RECORD, (name, id))


class AsyncQuerier:
    def __init__(self, conn: _AsyncDBAPIConnection):
        self._conn = conn

    async def delete_record(self, *, id: int) -> int:
        result = await self._conn.execute(DELETE_RECORD, (id,))
        return result.rowcount

    async def delete_records_returning(self, *, name: str) -> int:
        result = await self._conn.execute(DELETE_RECORDS_RETURNING, (name,))
        result.fetchall()
        return result.rowcount

    async def get_record(self, *, id: int) -> Optional[models.Record]:
        cursor = await self._conn.execute(GET_RECORD, (id,))
        row = cursor.fetchone()
        if row is None:
            return None
        return models.Record(
            id=row[0],
            name=row[1],
            note=row[2],
            payload=row[3],
            score=row[4],
            dynamic_value=row[5],
        )

    async def get_record_name(self, *, id: int) -> Optional[str]:
        cursor = await self._conn.execute(GET_RECORD_NAME, (id,))
        row = cursor.fetchone()
        if row is None:
            return None
        return cast(str, row[0])

    async def get_record_note(self, *, id: int) -> Optional[Optional[str]]:
        cursor = await self._conn.execute(GET_RECORD_NOTE, (id,))
        row = cursor.fetchone()
        if row is None:
            return None
        return cast(Optional[str], row[0])

    async def insert_record(self, arg: InsertRecordParams) -> Optional[models.Record]:
        cursor = await self._conn.execute(INSERT_RECORD, (arg.name, arg.note, arg.payload, arg.score, arg.dynamic_value))
        row = cursor.fetchone()
        if row is None:
            return None
        return models.Record(
            id=row[0],
            name=row[1],
            note=row[2],
            payload=row[3],
            score=row[4],
            dynamic_value=row[5],
        )

    async def list_record_notes(self) -> AsyncIterator[Optional[str]]:
        cursor = await self._conn.execute(LIST_RECORD_NOTES, ())
        result = cursor.fetchall()
        for row in result:
            yield cast(Optional[str], row[0])

    async def list_records(self, *, name: str) -> AsyncIterator[models.Record]:
        cursor = await self._conn.execute(LIST_RECORDS, (name, name))
        result = cursor.fetchall()
        for row in result:
            yield models.Record(
                id=row[0],
                name=row[1],
                note=row[2],
                payload=row[3],
                score=row[4],
                dynamic_value=row[5],
            )

    async def rename_record(self, *, name: str, id: int) -> None:
        await self._conn.execute(RENAME_RECORD, (name, id))
